name: Generate Datas
on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation with Customization
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: shant00
          svg_out_path: dist/github-contribution-grid-snake.svg
          # Example customization parameters
          color: '#007bff'  # Change the snake color
          grid_size: '16'   # Example grid size

      # List output directory for debugging
      - name: List output directory
        run: ls -la dist

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Check for errors
      - name: Check for errors
        if: failure()
        run: echo "The previous steps failed"
